---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '08:00'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
      time: '08:00'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    groups:
      bat-plugins:
        patterns:
          - ".config/bat/*"
      iterm2-plugins:
        patterns:
          - ".config/iterm2/*"
      neovim-plugins:
        patterns:
          - ".config/nvim/pack/*"
      tmux-plugins:
        patterns:
          - ".config/tmux/plugins/*"
      vim-plugins:
        patterns:
          - ".config/vim/pack/*"
      zsh-plugins:
        patterns:
          - ".config/zsh/*"
