brew "bat"
brew "curl"
brew "editorconfig"
brew "gh"
brew "gibo"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "lazygit"
brew "m-cli"
brew "mas"
brew "neofetch"
brew "neovim"
brew "openssl"
brew "pinentry-mac"  # For enter passphrase
brew "pygments"
brew "sl"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "xz"
brew "ykpers"  # Yubikey Personalization
brew "zsh"

# tap "homebrew/cask"  # Implemented as part of Homebrew
cask "1password"
cask "alt-tab"
cask "appcleaner"
cask "caffeine"
cask "cheatsheet"
cask "discord"
cask "divvy"
cask "docker"
cask "github"
cask "google-japanese-ime"
cask "iterm2"
cask "jordanbaird-ice"
cask "keybase"
cask "kindle"
cask "obsidian"
cask "visual-studio-code"

tap "homebrew/cask-fonts"
cask "font-meslo-lg-nerd-font"
