# Tap repositories and install packages
tap "homebrew/cask"
cask "1password"
cask "appcleaner"
cask "caffeine"
cask "cheatsheet"
cask "discord"
cask "divvy"
cask "docker"
cask "github"
cask "google-japanese-ime"
cask "iterm2"
cask "keybase"
cask "slack"
cask "visual-studio-code"
cask "witch"

tap "homebrew/core"
brew "curl"
brew "editorconfig"
brew "gibo"
brew "git"
brew "gnupg"
brew "lazygit"
brew "m-cli"
brew "mas"
brew "neofetch"
brew "openssl"
brew "pinentry-mac"  # For enter passphrase
brew "pygments"
brew "sl"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "xz"
brew "zsh"

tap "homebrew/cask-fonts"
cask "font-meslo-lg-nerd-font"

tap homebrew/autoupdate

# App Store applications
