"System
set nocompatible
set nobackup
set noswapfile
set autoread
set hidden
filetype off
syntax off
scriptencoding 'utf-8'

""Windows
if has('win32') || has('win64')
  "let $LANG='ja_JP.UTF-8'
  set shellslash
  set runtimepath+=$HOME/.vim
endif

"Terminal
set ttyfast

"Clipboard
set clipboard+=unnamed
set clipboard+=unnamedplus

"Keyboards
set backspace=indent,eol,start
set whichwrap=b,s,h,l,<,>,[,]
""leader keys
if has('mac')
  let mapleader = ","
endif
""Move cursor
nnoremap h <Left>
nnoremap j gj
nnoremap k gk
nnoremap l <Right>
nnoremap <Down> gj
nnoremap <Up> gk
"" :<->;
noremap ; :
noremap : ;
""Better window navigation
nnoremap <C-h> :<C-h>h
nnoremap <C-j> :<C-w>j
nnoremap <C-k> :<C-k>k
nnoremap <C-l> :<C-l>l
""Navigate buffers
noremap <S-h> <ESC>:bprevious<CR>
noremap <S-l> <ESC>:bnext<CR>
noremap <F2> <ESC>:bprevious<CR>
noremap <F3> <ESC>:bnext<CR>
noremap <F4> <ESC>:bwipeout<CR>
""Spacing after commma
inoremap , ,<Space>

"Mouse
if has("mouse")
  set mouse=a
endif
if !has("nvim")
  set ttymouse=xterm2
endif
set guioptions+=a

"Status
set showcmd
set showmode
set laststatus=2
set modelines=0
set cmdheight=1
"Display
set number
set ruler
set showmatch " ()
set lazyredraw
"" Show undisplay chars
set list
set listchars=tab:>.,trail:_,extends:>,precedes:<
"" Show cursor
set cursorline
augroup cch
  autocmd! cch
  autocmd WinLeave * set nocursorline
  autocmd WinEnter,BufRead * set cursorline
augroup END
"" Color
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

augroup TransparentBackGround
  autocmd!
  autocmd Colorscheme * highlight Normal ctermbg=NONE guibg=NONE
  autocmd Colorscheme * highlight NonText ctermbg=NONE guibg=NONE
  autocmd Colorscheme * highlight LineNr ctermbg=NONE guibg=NONE
  autocmd Colorscheme * highlight Folded ctermbg=NONE guibg=NONE
  autocmd Colorscheme * highlight EndOfBuffer ctermbg=NONE guibg=NONE
augroup END

"Indent
set autoindent
set smartindent
set cindent
set expandtab

set tabstop=4
set softtabstop=4
set shiftwidth=4

"Completion
set wildmenu
set wildchar=<Tab>
set wildmode=list:full
set history=1000
set complete+=k

"" Remove blank when close.
autocmd BufWritePre * :%s/\s\+$//ge

"Search
set wrapscan
set ignorecase
set smartcase
set incsearch
set hlsearch
set iminsert=0
set imsearch=0
""Cancelling highlight
nnoremap <ESC><ESC> :nohlsearch<CR>

"Multi bytes
set encoding=utf-8
set fileencodings=utf-8,cp932,euc-jp,default,latin
set fileformats=unix,dos,mac
if exists('&ambiwidth')
  set ambiwidth=single
endif
set formatoptions=lmoq
if has('syntax')
  syntax enable
  function! HighlightZenkakuSpace()
    highlight HighlightZenkakuSpace cterm=underline ctermfg=DarkGray gui=underline guifg=DarkGray
    silent! match HighlightZenkakuSpace /　/
  endfunction
  augroup HighlightZenkakuSpace
    autocmd!
    autocmd VimEnter,BufEnter * call HighlightZenkakuSpace()
  augroup END
endif
""IME off
set noimdisable
set noimcmdline
set iminsert=0
set imsearch=0
inoremap :set iminsert=0
"Disable IME in normal mode
augroup DisableImeInNormalMode
  autocmd!
  autocmd InsertEnter,CmdwinEnter * set noimdisable
  autocmd InsertLeave,CmdwinLeave * set imdisable
augroup END

"Plugin settings
""Airline
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_powerline_fonts = 1
let g:airline_theme = 'catppuccin_mocha'
let g:airline_left_sep = "\ue0b4"
let g:airline_right_sep = "\ue0b6"
let g:airline#extensions#hunks#non_zero_only = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#tabline#left_sep = "\ue0b4"
let g:airline#extensions#tabline#left_alt_sep = "\ue0b4"
""ALE
let g:ale_completion_enabled = 1
let g:ale_sign_column_always = 1
let g:ale_linters_explicit = 1
let g:ale_fix_on_save = 1
let g:ale_floating_window_border = ['│',  '─',  '╭',  '╮',  '╯',  '╰',  '│',  '─']
""" Use loclist instead of quickfix
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
highlight clear ALEErrorSign
highlight clear ALEWarningSign
let g:ale_sign_error = '**'
let g:ale_sign_warning = '!!'
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_info_str = 'I'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] [%severity%] %s (%code%)'
let g:ale_javascript_prettier_use_local_config = 1
let g:ale_python_flake8_change_directory = 'file'
let g:ale_ruby_rubocop_executable = 'bundle'
""" https://github.com/w0rp/ale/issues/925
let g:ale_linters = {}
let g:ale_linters['bash'] = ['shellcheck']
let g:ale_linters['css'] = ['eslint', 'stylelint']
let g:ale_linters['dockerfile'] = ['hadolint']
let g:ale_linters['go'] = ['gopls']
let g:ale_linters['html'] = ['eslint']
let g:ale_linters['javascript'] = ['eslint']
let g:ale_linters['json'] = ['jsonlint']
let g:ale_linters['python'] = ['flake8']
let g:ale_linters['ruby'] = ['rubocop']
let g:ale_linters['scss'] = ['stylelint']
let g:ale_linters['sql'] = ['sqlint']
let g:ale_linters['terraform'] = ['terraform', 'tflint']
let g:ale_linters['typescript'] = ['eslint']
let g:ale_linters['yaml'] = ['yamllint']
let g:ale_fixers = {}
let g:ale_fixers['bash'] = ['shfmt']
let g:ale_fixers['css'] = ['prettier', 'eslint']
let g:ale_fixers['go'] = ['gofmt']
let g:ale_fixers['html'] = ['prettier', 'eslint']
let g:ale_fixers['javascript'] = ['prettier', 'eslint']
let g:ale_fixers['json'] = ['prettier', 'eslint']
let g:ale_fixers['python'] = ['autopep8', 'autoflake']
let g:ale_fixers['ruby'] = ['rubocop']
let g:ale_fixers['scss'] = ['prettier', 'stylelint']
let g:ale_fixers['sql'] = ['sqlfmt']
let g:ale_fixers['typescript'] = ['prettier', 'eslint']
let g:ale_fixers['terraform'] = ['terraform']
let g:ale_fixers['yaml'] = ['actionlint', 'yamlfmt']
nnoremap <silent> <C-k> <Plug>(ale_previous_wrap)
nnoremap <silent> <C-j> <Plug>(ale_next_wrap)

""asyncomplete
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <CR>    pumvisible() ? asyncomplete#close_popup() : "\<CR>"
let g:asyncomplete_auto_popup = 1
let g:asyncomplete_popup_delay = 200

""Copilot
let g:copilot_filetypes = {}
let g:copilot_filetypes['gitcommit'] = v:true
let g:copilot_filetypes['markdown'] = v:true
let g:copilot_filetypes['yaml'] = v:true

""CtrlP
nnoremap <silent> ;; :CtrlPBuffer<CR>
nnoremap <silent> :: :CtrlP<CR>
if executable('ag')
  set grepprg=ag\ --vimgrep\ $*
  set grepformat^=%f:%l:%c:%m
  let g:ctrlp_user_command='ag %s -i --nocolor --nogroup -g ""'
  let g:ctrlp_use_caching = 0
endif

""Fern
let g:fern#disable_default_mappings = 1
let g:fern#renderer = 'nerdfont'

augroup my-fern-startup
  "Start fern.vim on Vim startup with a particular directory
  autocmd! *
  autocmd VimEnter * ++nested if !argc() | Fern . -drawer -reveal=% -width=40 -toggle | endif
augroup END

nnoremap <C-g> :<C-u>Fern . -drawer -reveal=% -width=40 -toggle<CR>

function! s:init_fern() abort
  "Perform open or collapse directory
  nmap <buffer><expr>
      \ <Plug>(fern-my-open-or-expand-collapse)
      \ fern#smart#leaf(
      \   "\<Plug>(fern-action-open)",
      \   "\<Plug>(fern-action-expand)",
      \   "\<Plug>(fern-action-collapse)",
      \ )
  nmap <buffer><nowait> o <Plug>(fern-my-open-or-expand-collapse)

  "Perform expand or collapse directory
  nmap <buffer><expr>
      \ <Plug>(fern-my-expand-or-collapse)
      \ fern#smart#leaf(
      \   "\<Plug>(fern-action-collapse)",
      \   "\<Plug>(fern-action-expand)",
      \   "\<Plug>(fern-action-collapse)",
      \ )
  nmap <buffer><nowait> l <Plug>(fern-my-expand-or-collapse)

  "Define NERDTree like mappings
  "nmap <buffer> o <Plug>(fern-action-open:edit)
  nmap <buffer> go <Plug>(fern-action-open:edit)<C-w>p
  nmap <buffer> t <Plug>(fern-action-open:tabedit)
  nmap <buffer> T <Plug>(fern-action-open:tabedit)gT
  nmap <buffer> i <Plug>(fern-action-open:split)
  nmap <buffer> gi <Plug>(fern-action-open:split)<C-w>p
  nmap <buffer> s <Plug>(fern-action-open:vsplit)
  nmap <buffer> gs <Plug>(fern-action-open:vsplit)<C-w>p
  nmap <buffer> ma <Plug>(fern-action-new-path)
  nmap <buffer> P gg

  nmap <buffer> C <Plug>(fern-action-enter)
  nmap <buffer> u <Plug>(fern-action-collapse)
  nmap <buffer> r <Plug>(fern-action-reload)
  nmap <buffer> R gg<Plug>(fern-action-reload)<C-o>
  nmap <buffer> cd <Plug>(fern-action-cd)
  nmap <buffer> CD gg<Plug>(fern-action-cd)<C-o>

  nmap <buffer> I <Plug>(fern-action-hidden-toggle)

  nmap <buffer> q :<C-u>quit<CR>
endfunction

augroup my-fern-custom
  autocmd! *
  autocmd FileType fern call s:init_fern()
augroup END

""glyph-palette
augroup glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
augroup END

""indent-guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1

""LSP
let g:lsp_signs_enabled = 1
let g:lsp_signs_error = {'text': '✗'}
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_settings_filetype_ruby = ['solargraph', 'steep']
function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
  if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
  nnoremap <buffer> gd <plug>(lsp-definition)
  nnoremap <buffer> gs <plug>(lsp-document-symbol-search)
  nnoremap <buffer> gS <plug>(lsp-workspace-symbol-search)
  nnoremap <buffer> gr <plug>(lsp-references)
  nnoremap <buffer> gi <plug>(lsp-implementation)
  nnoremap <buffer> gt <plug>(lsp-type-definition)
  nnoremap <buffer> <leader>rn <plug>(lsp-rename)
  nnoremap <buffer> [g <plug>(lsp-previous-diagnostic)
  nnoremap <buffer> ]g <plug>(lsp-next-diagnostic)
  nnoremap <buffer> K <plug>(lsp-hover)
  "nnoremap <buffer> <expr><c-f> lsp#scroll(+4)
  "nnoremap <buffer> <expr><c-d> lsp#scroll(-4)

  let g:lsp_format_sync_timeout = 1000
  autocmd! BufWritePre *.rs,*.go call execute('LspDocumentFormatSync')
  " refer to doc to add more commands
endfunction

augroup lsp_install
  au!
  " call s:on_lsp_buffer_enabled only for languages that has the server registered.
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

""Signify
nnoremap <leader>sd :SignifyDiff<cr>
nnoremap <leader>sp :SignifyHunkDiff<cr>
nnoremap <leader>su :SignifyHunkUndo<cr>
noremap <leader>sj <plug>(signify-next-hunk)
noremap <leader>sk <plug>(signify-prev-hunk)

""Test
nnoremap <silent> <leader>t :TestNearest<CR>
nnoremap <silent> <leader>T :TestFile<CR>
nnoremap <silent> <leader>a :TestSuite<CR>
nnoremap <silent> <leader>l :TestLast<CR>
nnoremap <silent> <leader>g :TestVisit<CR>
let test#strategy = "dispatch"
let test#vim#term_position = "belowright"

""Shutup
function s:ale_eslint_format(...)
  if &ft !~ 'typescript'
    return ''
  endif
  let value = a:000[0]
  let position = a:000[1]
  if position == 'upper' " Insert ignore into above current line.
    return printf('// eslint-disable-next-line %s', value)
  endif
  " Insert ignore into same line
  return printf(' // eslint-disable-line %s', value)
endfunction
function s:ale_py_format(...)
  if &ft !~ 'python'
    return ''
  endif
  let value = a:000[0]
  return printf('  # noqa: %s', a:000[0])
endfunction

function! s:load_shutup()
  let g:shutup_patterns = {
  \ '[eslint].*(\zs.*\ze)': function('s:ale_eslint_format'),
  \ '(\zs.*\ze)': function('s:ale_py_format'),
  \ }
  packadd shutup
endfunction

""Terraform - lazy load
function! s:load_terraform()
  let g:terraform_fmt_on_save = 1
  packadd terraform
endfunction

augroup lazy-load
  autocmd!
  autocmd FileType terraform call s:load_terraform()
  autocmd FileType javascript,python,typescript call s:load_shutup()
augroup END

"Colors
set background=dark
colorscheme catppuccin_mocha

syntax on
filetype plugin indent on
