require'nvim-treesitter.configs'.setup({
  ensure_installed = {
    'bash',
    'comment',
    'css',
    'csv',
    'diff',
    'dockerfile',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'html',
    'htmldjango',
    'java',
    'javascript',
    'jq',
    'jsdoc',
    'json',
    'jsonnet',
    'lua',
    'luadoc',
    'make',
    'markdown',
    'python',
    'requirements',
    'scss',
    'sql',
    'ssh_config',
    'terraform',
    'tmux',
    'toml',
    'typescript',
    'vim',
    'vimdoc',
    'yaml',
  },
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false
  },
  context_commentstring = {
    enable = true,
    enable_autocmd = false,
    config = {
      -- Languages that have a single comment style
      typescript = "// %s",
      css = "/* %s */",
      scss = "/* %s */",
      html = "<!-- %s -->",
      svelte = "<!-- %s -->",
      vue = "<!-- %s -->",
      json = "",
    },
  },
  indent = {
    enable = true,
    disable = {
      "python",
      "yaml",
    },
  },
})
