[default.extend-words]
# GIS / GeoSpatial
aoi = "aoi"
toi = "toi"
# Tech
iterm = "iterm"
# Others
eferences = "eferences"
ymbols = "ymbols"
rror = "rror"

[type.ignore]
extend-ignore-words-re = ["^[a-zA-Z]{1,3}$"]
